sudo: required
dist: trusty

language: node_js
node_js: 6

os:
  - linux
  - osx
  - windows

matrix:
  allow_failures:
    - os: windows

install:
  - npm install -g lix

script:
  - lix download
  - if [[ "$TRAVIS_OS_NAME" != "windows" ]]; then haxelib run travix python ; fi
  - haxelib run travix node
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then haxelib run travix js       ; fi
  - haxelib run travix java
  - haxelib run travix cpp
  - haxelib run travix cs
  - haxelib run travix php
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then haxelib run travix lua      ; fi
